# Generated by Django 3.2.10 on 2023-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_db',
            old_name='name',
            new_name='title',
        ),
    ]
