# Generated by Django 3.2.10 on 2023-08-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_blog_db_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_db',
            old_name='title',
            new_name='name',
        ),
    ]
