# Generated by Django 3.2.10 on 2023-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userregister_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('uemail', models.EmailField(blank=True, max_length=50, null=True)),
                ('upass', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
